name: Integração Contínua

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22'

      - name: Inicia banco
        run: docker compose up -d postgres

      - name: Espera banco iniciar (healthcheck manual)
        run: |
          echo "Aguardando Postgres iniciar..."
          for i in {1..50}; do
            if docker exec $(docker ps -qf "name=postgres") pg_isready -U root > /dev/null 2>&1; then
              echo "Postgres está pronto!"
              exit 0
            fi
            echo "Ainda iniciando... tentativa $i"
            sleep 2
          done
          echo "Postgres não iniciou a tempo."
          exit 1

      - name: Lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.59
          args: controllers/ database/ models/ routes/

      - name: Test
        run: |
          DB_HOST=${{ secrets.DB_HOST }} \
          DB_PASSWORD=${{ secrets.DB_PASSWORD }} \
          DB_USER=${{ secrets.DB_USER }} \
          DB_NAME=${{ secrets.DB_NAME }} \
          DB_PORT=${{ secrets.DB_PORT }} \
          go test -v main_test.go
